version: '3'
services:
  rabbitmq:
   image: rabbitmq:3-management-alpine
   container_name: 'rabbitmq'
   ports:
       - 5672:5672
       - 15672:15672
   volumes:
       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"